# Site settings
title: Fogo Tunde-Onadele
job.title: "Research Assistant"
email: oatundeo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  NC State University
  Department of Computer Science
  890 Oval Drive
  Engineering Building II
  Raleigh, NC 27695  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://fogo-t-o.github.io" # the base hostname & protocol for your site
#twitter_username: 
github_username:  oatundeo

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
#job.title: "Research Assistant"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""

# Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.
